apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-retain
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy : Retain
 

