---
apiVersion: v1
kind: Namespace
metadata:
  name: ${CUSTOMER_NAME}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
    customer: ${CUSTOMER_NAME}
  name: magento-svc
  namespace: ${CUSTOMER_NAME}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: magento-ui
  selector:
    app: magento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magento
    customer: ${CUSTOMER_NAME}
  name: magento
  namespace: ${CUSTOMER_NAME}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels: 
        app: magento
        customer: ${CUSTOMER_NAME}
    spec:
      containers:
      - image: ${DOCKER_IMAGE_DOMAIN_LOCALHOST}
        #imagePullPolicy: Never
        name: magento-pod
        env: 
        - name: BASE_URL
          value: "${BASE_URL}"
        - name: DB_HOST
          value: "${DB_HOST}"
        - name: DB_NAME
          value: "${DB_NAME}"
        - name: "DB_USER"
          value: "${DB_USER}" 
        - name: DB_PASS
          value: "${DB_PASS}" 
        - name: "ADMIN_FIRST_NAME"
          value: "${ADMIN_FIRST_NAME}"
        - name: "ADMIN_LAST_NAME"
          value: "${ADMIN_LAST_NAME}"
        - name: "ADMIN_EMAIL"
          value: "${ADMIN_EMAIL}"
        - name: "ADMIN_USERNAME"
          value: "${ADMIN_USERNAME}"
        - name: "ADMIN_PASSWORD"
          value: "${ADMIN_PASSWORD}"
        - name: "TIMEZONE"
          value: "${TIMEZONE}"
        - name: "CURRENCY"
          value: "${CURRENCY}"
        - name: "LANGUAGE"
          value: "${LANGUAGE}"
        - name: "BACKEND_FRONTNAME"
          value: "${BACKEND_FRONTNAME}"
        volumeMounts:
          - name: magento-storage
            mountPath: /var/www/html/magento2
      volumes:
      - name: magento-storage
        persistentVolumeClaim:
          claimName: magento-pv-claim 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pv-claim
  namespace: ${CUSTOMER_NAME}
spec:
  storageClassName: standard-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
