---
apiVersion: v1
kind: Namespace
metadata:
  name: customer1

---
apiVersion: v1
kind: Service
metadata:
  name: magento-customer1-external-svc
  labels:
    app: magento
    customer: customer1
  namespace: ingress
spec:
  type: ExternalName
  externalName: magento-svc.customer1.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: magento
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
    customer: customer1
  name: magento-svc
  namespace: customer1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: magento-ui
  selector:
    app: magento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magento
    customer: customer1
  name: magento-dep
  namespace: customer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels: 
        app: magento
        customer: customer1
    spec:
      containers:
      - image: magento-test
        imagePullPolicy: Never
        name: magento-pod
        env: 
        - name: DB_HOST
          value: "mysql.mysql"
        - name: DB_NAME
          value: "magento-customer1"
        - name: "DB_USER"
          value: "root" 
        - name: DB_PASS
          value: "root" 
        - name: "ADMIN_FIRST_NAME"
          value: "admin"
        - name: "ADMIN_LAST_NAME"
          value: "admin"
        - name: "ADMIN_EMAIL"
          value: "admin@admin.com"
        - name: "ADMIN_USERNAME"
          value: "admin"
        - name: "ADMIN_PASSWORD"
          value: "admin123"
        - name: "TIMEZONE"
          value: "Australia/Sydney"
        - name: "CURRENCY"
          value: "AUD"
        - name: "LANGUAGE"
          value: "en_US"
        - name: "BACKEND_FRONTNAME"
          value: "admin"
        volumeMounts:
          - name: magento-storage
            mountPath: /var/www/html/magento2
      volumes:
      - name: magento-storage
        persistentVolumeClaim:
          claimName: magento-pv-claim 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pv-claim
  namespace: customer1
spec:
  storageClassName: standard-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
