---
apiVersion: v1
kind: Namespace
metadata:
  name: customer2

---
apiVersion: v1
kind: Service
metadata:
  name: magento-customer2-external-svc
  labels:
    app: magento
    customer: customer2
  namespace: ingress
spec:
  type: ExternalName
  externalName: magento-svc.customer2.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: magento
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
    customer: customer2
  name: magento-svc
  namespace: customer2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
    name: magento-ui
  selector:
    app: magento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magento
    customer: customer2
  name: magento-dep
  namespace: customer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels: 
        app: magento
        customer: customer2
    spec:
      containers:
      - image: magento-test
        imagePullPolicy: Never
        name: magento-pod
        env: 
        - name: DB_HOST
          value: "mysql.mysql"
        - name: DB_NAME
          value: "magento-customer2"
        - name: "DB_USER"
          value: "root" 
        - name: DB_PASS
          value: "root" 
        - name: "ADMIN_FIRST_NAME"
          value: "admin"
        - name: "ADMIN_LAST_NAME"
          value: "admin"
        - name: "ADMIN_EMAIL"
          value: "admin@admin.com"
        - name: "ADMIN_USERNAME"
          value: "admin"
        - name: "ADMIN_PASSWORD"
          value: "admin1234"
        - name: "TIMEZONE"
          value: "Australia/Sydney"
        - name: "CURRENCY"
          value: "AUD"
        - name: "LANGUAGE"
          value: "en_US"
        - name: "BACKEND_FRONTNAME"
          value: "admin"
  
